[package]
name = "incrust-filters"
version = "0.6.0-dev.0"
authors = ["Alexander Irbis <irbis@irbis-labs.com>"]
license = "MIT/Apache-2.0"
description = "Composable formatting routines for the incrust template engine. Usable as a standalone crate."
keywords = ["format", "text"]
categories = ["text-processing", "template-engine", "value-formatting", "web-programming"]
readme = "README.md"
homepage = "https://github.com/irbis-labs/incrust"
repository = "https://github.com/irbis-labs/incrust"
documentation = "https://docs.rs/incrust/"
edition = "2024"
publish = false

[dependencies]
incrust-format = { path = "../format" }

#bstr = "1"
#log = "0.4"
#smart-string = "0.1.3"
#percent-encoding = "2"
#url = "2"
