[package]
name = "incrust-filters"
version = "0.6.0-dev.0"
authors = ["Alexander Irbis <irbis@irbis-labs.com>"]
license = "MIT/Apache-2.0"
description = "Composable formatting routines for the incrust template engine. Usable as a standalone crate."
keywords = ["format", "text"]
categories = ["text-processing", "template-engine", "value-formatting", "web-programming"]
readme = "README.md"
homepage = "https://github.com/irbis-labs/incrust"
repository = "https://github.com/irbis-labs/incrust"
documentation = "https://docs.rs/incrust/"
edition = "2024"
publish = false


[features]
default = []
full = [
    "FilterCase",
    "FilterHtml",
    "FilterUrl",
    "FilterXml",
]
FilterCase = []
FilterHtml = []
FilterUrl = [
    "percent-encoding",
]
FilterXml = []


[dependencies]
incrust-format = { path = "../format" }

percent-encoding = { version = "2", optional = true }
